### ISSUE TITLE
when run python autoptsclient-zephyr.py zephyr-master e:\zephyr.elf -t COM17 -b nrf52 -S 65000 -C 65001,error occurs

### ISSUE THREAD

**Issue by taotailiang** [auto-pts/auto-pts#1001]
![image](https://github.com/auto-pts/auto-pts/assets/33558032/1a59e670-0948-4e7b-91bf-ab957bde0042)
it says class pywintypes.com_error -2147352567

**Comment by mkasenberg** [comment]
It means that a PTS command throws an exception More context can be found in the generated autoptsserver_65000.log log file.

**Comment by sjanc** [comment]
reopen if this is stil an issue for you
