### ISSUE TITLE
All GATT tests report as `NOT_IMPLEMENTED`

### ISSUE THREAD

**Issue by jebanon** [auto-pts/auto-pts#1006]
Attempting to run a test on GATT profiles, all 51 return "NOT_IMPLEMENTED" I don't see a description anywhere of what this means? Does this mean auto-pts doesn't support testing these? Or that something is missing from my workspace file? Or something else?

```
(547940836816) OK
 1/51   GATT     GATT/CL/GAD/BV-01-C   NOT_IMPLEMENTED 0.0
 2/51   GATT     GATT/CL/GAD/BV-02-C   NOT_IMPLEMENTED 0.0
...
```

**Comment by mkasenberg** [comment]
Yes, this error means that for BlueZ there is no support for GATT tests yet. You can determine all supported profiles by looking into autopts/ptsprojects/bluez folder. For now there are only gap.py and sm.py files, meaning only GAP and SM are supported. Auto-pts client returned NOT_IMPLEMENTED because it could not found a gatt.py there.

**Comment by sciguy14** [comment]
Ok, understood - thank you. I don't suppose if you know if there exists any means for automatically testing GATT on BlueZ, or if I'm basically stuck running through every test case manually?

**Comment by mkasenberg** [comment]
No, I don't think there is one. But if you would like to implement the GATT support in BlueZ btpclient that would be great. Depending on how do you feel in C and Python, in my experience, it would take you a little more time than one or a few sessions of manual testing.

You can look up the btp client of Zephyr for comparision:
https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/bluetooth/tester/src
or MyNewt Nimble one:
https://github.com/apache/mynewt-nimble/tree/master/apps/bttester/src

If you feel up to it, I'll be happy to help and answer your questions.
