### ISSUE TITLE
Fail to register endpoint in bluez5.66

### ISSUE THREAD

**Issue by handomzhu** [auto-pts/auto-pts#1040]
Hi, guys,
I followed the instruction of setting up LE audio in ubuntu22.04, with bluez5.66 installed.
but I failed to register endpoint like this:
![image](https://github.com/auto-pts/auto-pts/assets/14226882/124050fc-ce27-40fb-9790-5fe39621bc06)

If you meet this problem and solve it, please let me know, thanks.

**Comment by sjanc** [comment]
I don't see how this is related to autopts,    perhabs you should report it on bluez github?
