### ISSUE TITLE
README refers to old Zephyr slack channel

### ISSUE THREAD

**Issue by Thalley** [auto-pts/auto-pts#1122]
At the bottom of the README, there's a reference and a link to the old Zephyr Slack channel, which doesn't exist anymore, and should be removed.

Ideally it should be replaced by a comparable channel in the Zephyr Discord, but there are no AutoPTS channel there (yet).

**Comment by MicImbriani** [comment]
Is there anything preventing us from creating such a channel on the Zephyr Discord server?

**Comment by Thalley** [comment]
> Is there anything preventing us from creating such a channel on the Zephyr Discord server?

Probably not :)
