### ISSUE TITLE
hid and related libraries not installed with autoptsserver_requirements.txt

### ISSUE THREAD

**Issue by MicImbriani** [auto-pts/auto-pts#1212]
If the steps in the README are followed, the workspace does not get set up correctly.
In fact, after running the ` python.exe -m pip install --user -r autoptsserver_requirements.txt`, all the dependencies should be met. However, when running the autoptsserver, the following Import Error is shown:

`ImportError: No module named hid`

**Comment by piotrnarajowski** [comment]
Hello,
thanks for letting know. autoptsserver_requirements.txt and autoptclient_requirements.txt will be updated. Just make sure you don't have installed both hid and hidapi module - the former might be interrupting loading hidapi. Let me know if you encounter any other issues.

**Comment by MicImbriani** [comment]
I can see that the files have been updated by [PR#1214](https://github.com/auto-pts/auto-pts/pull/1214). 
Closing this issue.
