### ISSUE TITLE
Show pass/fail tests count in PR comment

### ISSUE THREAD

**Issue by sjanc** [auto-pts/auto-pts#1256]
Currently when running bot against PR one get summary info of total tests count to be run, but comments with results is missing count on pass/failed

AutoPTS Bot results:

<details>
<summary>Failed tests</summary>
<br>
BAP BAP/BA/CGGIT/CHA/BV-01-C BTP ERROR

BAP BAP/BA/CGGIT/CHA/BV-02-C BTP ERROR
</details>
<details>
<summary>Successful tests</summary>
<br>
BAP BAP/BA/CGGIT/SER/BV-01-C PASS
</details>

Would be nice to have this as:
<details>
<summary>Failed tests (2)</summary>
<br>
BAP BAP/BA/CGGIT/CHA/BV-01-C BTP ERROR

BAP BAP/BA/CGGIT/CHA/BV-02-C BTP ERROR
</details>
<details>
<summary>Successful tests (1)</summary>
<br>
BAP BAP/BA/CGGIT/SER/BV-01-C PASS
</details>

**Comment by piotrnarajowski** [comment]
Fixed - https://github.com/auto-pts/auto-pts/pull/1260
