### ISSUE TITLE
infinite loop in the synchronize_instances() after the autoptsserver exception and recovery

### ISSUE THREAD

**Issue by Sparrowbe** [auto-pts/auto-pts#442]
Dears,

I have experienced an infinite loop in the `autoptsclient` after a server-side exception. The sequence is as follows:
- somewhere in the middle of a test execution, the PTS dongle becomes unavailable for the PTS process (I suspect power managment of the MS Windows is responsible for that but it is not relevant to the main problem I'm describing here)
- after several tests executed (each of them resulting in the pts_recovery), I make the dongle responsive again
- the autoptsclient is eventually stuck with an infinite loop, trying to synchronize the state of several test cases

From what I have identified (with help of several extra log entries added locally), the client-side of the framework waits for the test case to finish in
```
        for pts_thread in pts_threads:
            pts_thread.join()
```
but there is an exception on the server side within the `try:` section of the `run_test_case_thread_entry()` (in `test_case.pre_run()`). Then there is an attempt to `pts.recover_pts()` in the `finally:` section, but the server throws another exception (unhandled on the client's side, this time) that causes the client thread to skip following part of the `run_test_case_thread_entry()`:
```
        test_case.state = "FINISHING"
        synchronize_instances(test_case.state)
        test_case.post_run(error_code)  # stop qemu and other commands
        del RUNNING_TEST_CASE[test_case.name]
```
so the `RUNNING_TEST_CASE` contains entries for unfinished test cases and the content of that dict builds up over time (because of the exceptions described above).

Eventually, the cause of the server's exceptions is fixed and the next client's thread is able to proceed to `synchronize_instances(test_case.state)` but by that time the `RUNNING_TEST_CASE` has number of entries in the `PRE_RUN` state for already interrupted test cases, causing the `while True:` loop to never meet the exit criteria.

[console.log](https://github.com/intel/auto-pts/files/6296393/console.log)
[autoptsclient.log](https://github.com/intel/auto-pts/files/6296396/autoptsclient.log)

As exceptions from a child thread are not propagated to the main one, could the `autoptsclient_common` module explicitly handle exceptions that may occur during the PTS recovery? I suppose, the whole test suite execution could be interrupted on non-recoverable problem with the PTS server.

**Comment by sjanc** [comment]
this has been heavily refactored in past few months, feel free to reopen if this is stil an issue for you
