### ISSUE TITLE
Optimize code size: get rid of unused GATT characteristics in Zephyr databases

### ISSUE THREAD

**Issue by KKopyscinski** [auto-pts/auto-pts#476]
Since Zephyr supports EATT, in which minimum MTU is 64, term "long characteristic" changed it's meaning. PR https://github.com/intel/auto-pts/pull/475 fixed tests requiring such characteristics, that are longer than they were before. After it, many "long" characteristics from `init_server_{1...4}` might be unused. TODO: check if any of these characteristics are obsolete and remove them.

**Comment by sjanc** [comment]
should be fixed by https://github.com/auto-pts/auto-pts/pull/893

**Comment by KKopyscinski** [comment]
@sjanc Looks like it :) I think we can close this after merge
