### ISSUE TITLE
after pull the latest auto-pts console has garbled code

### ISSUE THREAD

**Issue by justin-nxp** [auto-pts/auto-pts#819]
I have update the auto-pts but when I ran ， it get the garbled code ，does I missing some modules？
![image](https://user-images.githubusercontent.com/109336628/197165416-5e0eff07-8297-48f5-89ef-1aeb9a40944a.png)

**Comment by mkasenberg** [comment]
Probably fixed with #906.

**Comment by sjanc** [comment]
Please reopen if this is stil an issue
