### ISSUE TITLE
Case GAP/SEC/AUT/BV-27-C has no attribute 'hdl_wid_108'

### ISSUE THREAD

**Issue by justin-nxp** [auto-pts/auto-pts#828]
![image](https://user-images.githubusercontent.com/109336628/201820491-95444c95-12ee-4e85-98a5-97c09d2735a7.png)

**Comment by sjanc** [comment]
wid_108 is implemented in generic WID handler (autopts/wid/gap.py)

please check your installation (ie paths and if no files are missing) as this test is working on our weekly runs

**Comment by sjanc** [comment]
is this stil an issue?

**Comment by sjanc** [comment]
I reworked a bit handling of those wids,  if this is stil an issue for you please reopen
