### ISSUE TITLE
mannual passed cases

### ISSUE THREAD

**Issue by justin-nxp** [auto-pts/auto-pts#833]
Hi there,I have noticed that some case test pass with mannual , can I have a list of mannual passed cases

because  I found those case in the report PASS
GATT    GATT/SR/GAW/BV-12-C             PASS
GATT    GATT/SR/GAW/BV-13-C             PASS
GATT    GATT/SR/GAW/BV-14-C             PASS

But I set the same branch get a INCONC

**Comment by sjanc** [comment]
assing in latest runs
