### ISSUE TITLE
Case changed some cases not support

### ISSUE THREAD

**Issue by justin-nxp** [auto-pts/auto-pts#836]
I have noticed that the SIG changed the case of workspace in autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

Newly emerging
GATT/CL/GAN/BV-02-C
GATT/CL/GAR/BI-36-C
GATT/CL/GAR/BI-38-C
GATT/CL/GAR/BI-40-C
GATT/CL/GAR/BI-42-C
GATT/CL/GAR/BI-44-C
GATT/CL/GAR/BV-08-C
GATT/CL/GAR/BV-10-C
GATT/CL/GAR/BV-11-C
GATT/CL/GAS/BV-05-C
GATT/CL/GAT/BV-03-C
GATT/SR/GAN/BV-02-C
GATT/SR/GAR/BI-36-C
GATT/SR/GAR/BI-38-C
GATT/SR/GAR/BI-40-C
GATT/SR/GAR/BI-42-C
GATT/SR/GAR/BI-44-C
GATT/SR/GAR/BV-09-C
GATT/SR/GAR/BV-11-C
GATT/SR/GAR/BV-12-C
GATT/SR/GAS/BV-08-C

Remove
GATT/CL/GAW/BI-32-C
GATT/CL/GAW/BV-06-C

**Comment by sjanc** [comment]
fixed
